name: Release next version
run-name: Release version ${{ inputs.releaseVersion }}
on:
  workflow_dispatch:
      inputs:
          releaseVersion:
              description: 'Version number to use for this release'
              required: true
              default: '2.x.x'
          releaseNoteUrl:
              description: 'Enter the location of edited release notes to use'
              required: false
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                ref: 'dev'
            - name: Generate Release notes
              if: ${{ github.event.inputs.releaseNoteUrl == '' }}
              run: >
                echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token;
                gh release view $(basename $(gh release create v${{ github.event.inputs.releaseVersion }} --title "Release ${{ github.event.inputs.releaseVersion }}" --draft --generate-notes)) > temp_change.md
            - name: Use existing Release notes
              if: ${{ github.event.inputs.releaseNoteUrl != '' }}
              run: >
                echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token;
                gh release view $(basename ${{ github.event.inputs.releaseNoteUrl }}) > temp_change.md
            - name: Tweak changelogs
              run: |
                # Remove carriage returns to be able to run the script
                sed -i 's/\r$//' .github/tweak_changelogs.sh
                chmod +x .github/tweak_changelogs.sh
                .github/tweak_changelogs.sh "v${{ github.event.inputs.releaseVersion }}"
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5
              with:
                  draft: true
                  title: Release ${{ github.event.inputs.releaseVersion }}
                  branch: release-${{ github.event.inputs.releaseVersion }}
                  body: |
                      Draft release of ${{ github.event.inputs.releaseVersion }}.

                      Edits will be made as necessary to prepare the codebase for release.
                  commit-message: 'Prepare release ${{ github.event.inputs.releaseVersion }}'
